[quote.epigraph, , Prov. 10:7]
____
The memory of the just is blessed.
____

[quote.epigraph, , John 6:12]
____
Gather up the fragments that remain, that nothing be lost.
____

== Introduction

When the Christian example of those we love is withdrawn,
and we are no longer cheered by their conversation, or instructed by their admonitions,
we recur with satisfaction to those instances of faithfulness which memory furnishes;
but when assisted by written records of their devout and exercised minds,
they become enhanced in value,
and we esteem them as precious memorials of departed worth.

Such we believe will be the feelings of many who
have known and loved the subject of this short memoir,
the reader will find for his instruction and encouragement,
that in the simplicity and sincerity of her heart,
she has unfolded some of her mental exercises;
and as they breathe throughout the language of piety
and resignation under deep and complicated trials,
they will, it is hoped, afford consolation to those in similar circumstances,
seeing it was by the grace of God she was what she was,
and to the sustaining power of his grace,
she bore testimony during a long protracted life.

In the relation of a mother few exceeded her in tenderness,
and she endeavoured to attain to Christian resignation when bereaved of her children,
six of whom died at different periods +++[+++before her.]

Instructed in the school of adversity, and possessing a sympathetic mind,
she was peculiarly qualified to impart consolation to the weary traveller Zionward,
and to extend the hand of encouragement to those who had wandered from
the true Shepherd--endeavouring to comfort those who were in any trouble,
by the comfort wherewith she herself was comforted of God.

Deeply impressed with gratitude for the blessings
with which the evening of her day was crowned,
and with a mind reconciled to the dispensations of Providence in earlier life,
she often dwelt in feeling remembrance upon the mercies she had experienced,
and to almost the latest period,
her conversation and manners partook of the cheerfulness
and pleasantness of her meridian life.
When the awful time arrived in which she was permitted to enter her eternal rest,
she passed away in sweet serenity, full of days and full of peace,
and we humbly believe her redeemed spirit is numbered
with those who came out of great tribulations,
and have washed their robes, and made them white in the blood of the Lamb.

Ashford, Eighth month, 1841.
