[short="A Testimony from Folkstone Monthly Meeting"]
== A Testimony from Folkstone monthly meeting, concerning Mary Hagger, deceased.

In preserving a memorial of this our dear friend,
we are instructively reminded of her meek and lowly example.
She was desirous to be found adorning the doctrine of God her Saviour in all things;
that her rejoicing might be this, the testimony of her conscience,
that with simplicity and godly sincerity, not with fleshly wisdom,
but by the grace of God, she conducted herself in the world.

She was the daughter of our friends, William and Lettice Knight,
and was born at Stone-hall, near Wanstead, Essex, the 4th of first month, 1758.

The following selections from her memoranda, show the early pious concern of her parents:
"`I was blessed with tender parents,
that watched over themselves and their family with a religious care,
taking us to meetings; and were very diligent attenders themselves,
though residing at a distance of several miles,
the weather or business seldom if ever preventing.`"

She thus adverts to her religious feelings in early life;
"`I well remember being in a garden by myself,
and knew not what it was that so sweetened and tendered my heart,
that for a considerable time I felt as though I could not leave the spot,
and several times afterwards I took opportunities to retire, and had similar feelings.`"
"`As I grew, I often felt the prevalence of my natural disposition,
giving way to indifference in things relating to my best interest,
so that I often desired something might befall me,
to arouse me from such a spirit of ease and unconcernedness; and after awhile,
kind Providence,
whose peculiar care is extended over us while passing the slippery paths of youth,
inclined my heart to love him,
and permitted me to have an illness which continued some weeks,
and in degree awakened me.`"

She had to pass through many painful conflicts,
often lamenting the lack of an entire surrender of heart to the refining
hand of him who was preparing her as a vessel for his service.
She was impressed with a belief that it would be required
of her to bear public testimony to the goodness of the Lord;
but from this sacrifice, she earnestly desired she might be spared;
and the language of her heart was, "`Send by whom you will send, but not by me.`"
She yielded however, to this religious conviction,
by giving up to speak a few words in meetings for
discipline when she apprehended it required of her.

On the subject of these meetings, she remarks,
"`I believe that if the discipline is rightly supported,
it must be by the influence of the same power that moves to every duty.`"

While struggling with severe outward trials, she sought to cherish a tender conscience,
and by adhering to Christian principle,
her conduct became remarkable for strict integrity;
and after being brought through her temporal difficulties, by the power of divine grace,
she was raised up an instrument of usefulness in the church.
Abiding in deep watchfulness and humble dependence on the Lord,
to know his putting forth to the solemn work,
she became qualified to speak a word in season to the weary in Zion,
and at times was strengthened to "`lift up the banner on the high mountain.`"
Her offerings in the ministry being expressed in few words,
and in great diffidence and fear, were impressive,
evincing that she sought not honour from man, but that which comes from the Lord alone.

In 1831, she visited by certificate the meetings in Bedfordshire and Hertfordshire,
as also the families of Friends in Hertford.
In the following year,
she paid a similar visit to the monthly meetings in the county of Nottingham,
and in 1835, to those composing the quarterly meeting of Essex:
these services proved acceptable to her friends, and afforded peace to her own mind.

She felt much interested in objects of Christian philanthropy: the poor and afflicted,
more especially, obtained her commiseration.
She cherished a deep solicitude for the religious welfare of her near connections in life;
desiring that they, as well as herself, might experience a growth in grace,
and in the knowledge of our Lord and Saviour Jesus Christ.
She thus expresses her feelings on this all-important subject;
"`I pray for myself and my dear children,
that we may be strengthened in an unshaken belief in the
efficacy of the blood of the beloved Son of God,
our Lord and Saviour Jesus Christ; who came down from heaven,
and took not upon him the nature of angels, but the seed of Abraham;
was born of the Virgin Mary; suffered under Pontius Pilate,
the cruel and shameful death of the cross,
to be a propitiation and atonement for the sins of the whole world,
rose again the third day from the dead, and ascended into heaven,
and is the Advocate and Mediator between God and man, the King, High Priest,
and Prophet of his church,
and the author of salvation to all that obey him;--true God and perfect man.`"

At the latter end of 1835, our dear friend was visited with severe illness,
from which her recovery then appeared very doubtful;
but she was favoured to be restored to usual health,
until the close of the following year;
when she was seized with another alarming attack which greatly reduced her strength;
yet she so far recovered,
as to be able to assemble with her friends at religious meetings,
though often under great bodily infirmity.

During the illness above alluded to, her mind was much clothed with love,
and her expressions were often weighty and instructive.
After passing a low and deeply depressing season, she said, "`Should I be taken now,
all will be well; I have a full assurance there is a mansion prepared for me,
and that crowns all.`"
At another time, "`It is an awful thing to appear before the Judge of the whole earth;
and I am sure I have not a rag or anything, to cover myself with;
but my whole and entire dependence is on my holy Saviour,
who I humbly hope will plead my cause.
I do believe love will cover the judgment seat.
If there are any that slight the offers of a merciful Saviour,
how deplorable must be their condition!`" "`I have
felt the Comforter at the threshold of the door,
waiting to do his own office.`"

At different times, she expressed as follows, "`I feel very low:
I want to feel more of my heavenly Father`'s presence.
O! I do most fervently hope, if there are any sins yet remaining, they may be blotted out.
O! how unworthy!
I feel that I have not a good act of my own that I can plead;
but my dear Saviour died for me; and I have a hope, that he will receive me,
not of works, but of his free grace.`"
To one of her family whom she had not seen for several days, she said,
"`I want to tell you the bands are broken, and I feel great liberty in the Truth,
and can sometimes sing high praises.`"
At another time, "`O! that it may please my heavenly Father to say, it is enough,
and take his poor, I am almost afraid to say servant to so high a power, to himself.`"

Our beloved friend for many years suffered from a violent nervous affection of the head,
accompanied with a distressing cough, which greatly exhausted her enfeebled frame,
so that from the spring of 1839 to the ensuing autumn,
she was almost wholly confined to the house.
In the ninth month of that year, she received a visit from her only surviving brother,
who, after a few days`' illness, died at her house.
After this sudden and unexpected event, her health rapidly declined,
and she suffered much at times from mental depression,
yet was favoured to know her heart stayed on the Lord.
At one time she said, "`O that I may die the death of the righteous,
and that my last end may be like theirs!
I have a hope that casts out fear.
I have a hope both sure and steadfast.`"

A few days before the final close, when alluding to the death of our blessed Saviour,
she observed, "`I must die the death: mine is a natural death,
but his was for the whole world.
He gave up his life freely, and suffered on the cross:
He gave his life a willing sacrifice, and we must give up our whole hearts.
'`No Cross no Crown,`' is a sure testimony, and will be answered in a future day;
if we will not bear the cross, we cannot have the crown.`"
Then addressing her children present, said, "`O, my dear children,
from my dying bed I beg of you, that it may be the constant breathing of your souls,
to be redeemed from the perishing things of time,
and that your affections may be fixed on eternity.
What would it avail now, or at any other time, to have the world,
or as much as might be equal to our extravagant desires, to possess?
I would freely give it up for a happy possession +++[+++in heaven.]
Oh press after it, do not be satisfied in anything that is sensual or carnal, but oh,
that we may press after an inheritance in that which will endure forever!`"

Nearly her last expressions were,
"`Oh eternity!--Oh the length of eternity!--Oh that it may be impressed on every heart,
the length of eternity! there is no end.`"

She peacefully expired on the 25th day of the 1st month, 1840, aged about 82 years,
and is, we have no doubt, through the blood of the everlasting covenant,
gathered to the just of all generations,
to unite in ascribing salvation to him that sits on the throne,
and to the Lamb forever more.

Her remains were interred in Friends`' burial ground at Ashford,
on the 2nd day of second month, 1840.

Given forth by Folkstone monthly meeting, held at Canterbury,
the 12th of the third month, 1840.
